name: opencalc
description: Minimalistic and cute calculator.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  logger: ^1.1.0
  bloc: ^8.1.0
  bloc_test: ^9.1.0
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  fast_immutable_collections: ^7.4.1
  hydrated_bloc: ^8.1.0
  path_provider: ^2.0.11
  math_parser: ^1.5.0
  flex_color_scheme: ^6.0.0
  fpdart: ^0.2.0
  drift: ^2.1.0
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.2
  auto_route: ^5.0.1
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0
  drift_dev: ^2.1.0
  lint: ^1.10.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  auto_route_generator: ^5.0.2

flutter:
  uses-material-design: true